name: Run Artillery with Playwright Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-testing-and-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build the Vite project
      - name: Build project
        run: npm run build

      # Start the backend server in the background
      - name: Start backend server
        run: nohup npm run backend &

      # Ensure the results directory exists
      - name: Create results directory
        run: mkdir -p ./artillery-results

      # Run the first Artillery load test
      - name: Run basic load test
        run: npx artillery run load-tests/artillery-basic.yml --output ./artillery-results/report.json

      # Run the second Artillery load test
      - name: Run shopping load test
        run: npx artillery run load-tests/artillery-shopping.yml --output ./artillery-results/report.json

      # Run the third Artillery load test with Playwright integration
      - name: Run shopper load test with Playwright
        run: npx artillery run load-tests/playwright-shopping.yml --output ./artillery-results/report.json

      # Upload Artillery results as artifacts
      - name: Upload results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artillery-results
          path: ./artillery-results

      # Display Artillery results
      - name: Display results
        run: |
          cat ./artillery-results/basic-report.json
          cat ./artillery-results/shopping-report.json
          cat ./artillery-results/playwright-shopping-report.json
