name: Run Artillery with Playwright Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-testing-and-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      # Start the backend server in the background
      - run: nohup node backend/index.js &

      # Run Artillery tests and generate JSON and HTML reports
      - name: Run Artillery test with Playwright
        run: |
         npx artillery run load-tests/playwright-test.yml --output ./artillery-results/report.json

      # Upload Artillery results as artifacts, even if the tests fail
      - name: Upload results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artillery-results
          path: ./artillery-results

      # Optionally, display the results of the tests
      - name: Display results (JSON format)
        run: cat ./artillery-results/report.json
